services:
  - type: web
    name: innventa-ai-chatbot
    env: node
    buildCommand: npm install; npm run build
    startCommand: node render-free-tier.cjs
    envVars:
      - key: NODE_ENV
        value: production
      - key: OPENAI_API_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: EXTERNAL_URL
        value: "https://innventa-ai-chatbot.onrender.com/health"
    plan: free # 512MB RAM, 0.1 CPU
    branch: main
    region: oregon
    numInstances: 1
    healthCheckPath: /health