services:
  - type: web
    name: innventachat-ai
    env: node
    repo: https://github.com/your-github-repo/innventa-chatbot.git # Replace with your actual repo URL
    buildCommand: npm install && npm run build
    startCommand: node server.js
    healthCheckPath: /health
    envVars:
      - key: VERIFY_TOKEN
        value: innventa_secure_token
      - key: NODE_ENV
        value: production
    plan: free